### ISSUE TITLE
Twitter count http://urls.api.twitter.com no longer available

### ISSUE THREAD

**Issue by leanazulyoro** [palamago/shared-links-ranking#30]
Twitter's _non-supported_ public api is  no longer online (https://blog.twitter.com/2015/hard-decisions-for-a-sustainable-platform), thus any call to http://urls.api.twitter.com returns 404, resulting in no twitter count, apparently the is not official API method to get a share count for a given URL. I'm gessing we cound use the search api method to get tweets that contain a given url in it's text.

I'm wondering how are you still able to get the count for http://topranking.link/ar#/

**Comment by palamago** [comment]
Site is not availbable anymore.
